name: "Automatic release with tag"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    if: github
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#newVersion')}}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Update project version
        env:
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          NAME: github-actions[bot]
        run: ./.github-cli/update-version

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/statique.zip
