name: "Automatic release with tag"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#newVersion')}}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Update project version
        env:
          GIT_VERSION: ${{ github.ref_name }}
        run: ./.github-cli/update-version

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install


      - name: Build the doc
        run: mvn javadoc:jar

      - name: Rename jar to zip
        run: ./.github-cli/javadoc-prepare

      - name: Commit version change
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pom.xml src/main/resources/about/version.txt'
          author_name: github-action[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'automatic version update to ${{ github.ref_name }} #newVersion'
          tag: "${{ github.ref_name }} --force"
          tag_push: '--force'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/statique.zip
            target/statique-javadoc.zip
